region: eu-west-1 
  
credentials:
  key: awsinblah-cd-aws-access-key-id-prod
  secret: awsinblah-cd-aws-secret-access-key-prod
           
consul:
  httpaddr: https://consul-coe-cicd.inh-apps.eu.boehringer.com
  httptoken: awsinblah-cd-consul-http-token

