exclude: '.terraform'
fail_fast: true

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v3.4.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=5000]
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: detect-aws-credentials
    args: [--allow-missing-credentials]
  - id: detect-private-key
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: pretty-format-json
    args: [--autofix, --indent=2, --no-ensure-ascii]
  - id: trailing-whitespace

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.45.0
  hooks:
  - id: terraform_fmt
  - id: terraform_docs

- repo: ssh://git@bitbucket.biscrum.com:7999/infiaas/pre-commit-hooks-terraform.git
  rev: v1.5.0
  hooks:
  - id: terraform_inputs_jenkins_pipeline_params
    language_version: python3
    args: ['--replacements={ "params.name": "convertToName(params.name.toString())" }']
    files: variables.tf

- repo: local
  hooks:
  - id: test
    name: make test
    description: Run integration tests.
    entry: make test
    language: system
    files: (\.tf|\.rb)$
    pass_filenames: false
    verbose: true

